### ISSUE TITLE
Make `OAS_PATH` the actual path to the specs

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-oas-renderer#14]
This tool expects an environment variable called `OAS_PATH` which we've documented as being the location where the API specs are. In fact, the specified location must contain a `definitions/` folder with the specs in there. Could we make this so that the path is actually the path without any hardcoded element, so people can call their directories whatever they like?

**Comment by fabianrbz** [comment]
Closing, this has been fixed by https://github.com/Nexmo/nexmo-oas-renderer/pull/36
