### ISSUE TITLE
What do the constraints mean outside of NDP

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-oas-renderer#15]
I'm trying to blog about our OAS tooling and share what we've made but I'm still seeing things like https://github.com/Nexmo/nexmo-oas-renderer/blob/69969ee354e83ecbd37bb492eced9ef14c050538/lib/nexmo/oas/renderer/constraints/open_api.rb in the codebase. Does this affect naming of the files that can be rendered or anything?

Related a bit to #14 where for a user with an `open_api.yml` file, it's a bit counterintuitive if there's extra expectations.

**Comment by fabianrbz** [comment]
Related #35
