### ISSUE TITLE
Match new Webhooks OpenAPI Feature

### ISSUE THREAD

**Issue by lornajane** [Nexmo/nexmo-oas-renderer#46]
We use `x-webhooks` at the top level of our specs (see SMS spec), but the new feature that has been accepted into OpenAPI has a slightly different structure with `webhooks` at the top level and no URL entry. An example is here: https://github.com/OAI/OpenAPI-Specification/blob/61f9d7e2398dfb1c1211ca30af3a5331cd3863d2/examples/v3.1/webhook-example.yaml

**Comment by lornajane** [comment]
Ping @fabianrbz @mheap I know everyone is busy but is this something we could take a look at and figure out how much time we'd need to make this change? I think only the SMS spec actually uses this at the moment although I'd love to get other webhooks documented once we're updated. It _looks_ like a simple syntax change (I can open the draft PR for SMS if that helps) but I don't know the internals so I don't want to assume it's as simple as it looks!!

**Comment by mheap** [comment]
Resolved in #65
